# -*-python-*-

from SCons.Errors import EnvironmentError

try:
    Import("env")
    pyenv = env.Clone(tools = ['pybind11'])

    pyenv.AppendUnique(LIBS  = ['statiskit_glm'])
    if env['SYSTEM'] == 'linux':
        pyenv.AppendUnique(CCFLAGS = ['-Wno-attributes', '-Wno-ignored-attributes'])
    elif env['SYSTEM'] == 'osx':
        pyenv.AppendUnique(CCFLAGS = ['-Wno-delete-non-virtual-dtor'])

    exclude = """
    """.split()

    sources = [source for source in pyenv.Glob('*.*') if source.name not in exclude]

    targets = pyenv.PyBind11Extension("../statiskit/glm/__glm", sources)
    Alias("py", targets)
    Alias("install", targets)
    pyenv.Depends(targets, "cpp")
    
    targets = pyenv.PythonPackage(statiskit = '../statiskit')
    Alias("py", targets)
    Alias("install", targets)
    pyenv.Depends(targets, "cpp")
except EnvironmentError:
    Alias("py", [])
    Alias("install", [])
    pass
except Exception:
    raise