#include "_glm.h"

struct ::statiskit::glm::CategoricalFisherInitialization & (::std::unique_ptr< ::statiskit::glm::CategoricalFisherInitialization, ::std::default_delete< ::statiskit::glm::CategoricalFisherInitialization > >::*method_pointer_5f48b92827795a319b60334e5683e78a)()const= &::std::unique_ptr< struct ::statiskit::glm::CategoricalFisherInitialization, struct ::std::default_delete< struct ::statiskit::glm::CategoricalFisherInitialization > >::operator*;
::std::unique_ptr< struct ::statiskit::glm::CategoricalFisherInitialization, struct ::std::default_delete< struct ::statiskit::glm::CategoricalFisherInitialization > >::pointer  (::std::unique_ptr< ::statiskit::glm::CategoricalFisherInitialization, ::std::default_delete< ::statiskit::glm::CategoricalFisherInitialization > >::*method_pointer_74edbedca9aa5d5991a941c13582659b)()const= &::std::unique_ptr< struct ::statiskit::glm::CategoricalFisherInitialization, struct ::std::default_delete< struct ::statiskit::glm::CategoricalFisherInitialization > >::get;
::std::unique_ptr< struct ::statiskit::glm::CategoricalFisherInitialization, struct ::std::default_delete< struct ::statiskit::glm::CategoricalFisherInitialization > >::pointer  (::std::unique_ptr< ::statiskit::glm::CategoricalFisherInitialization, ::std::default_delete< ::statiskit::glm::CategoricalFisherInitialization > >::*method_pointer_6d0ffb4b2ff959a3afe6ca2111e554b8)()= &::std::unique_ptr< struct ::statiskit::glm::CategoricalFisherInitialization, struct ::std::default_delete< struct ::statiskit::glm::CategoricalFisherInitialization > >::release;
void  (::std::unique_ptr< ::statiskit::glm::CategoricalFisherInitialization, ::std::default_delete< ::statiskit::glm::CategoricalFisherInitialization > >::*method_pointer_3bcf3d26f42a5e818cd5729b7e3bfe8d)(::std::unique_ptr< struct ::statiskit::glm::CategoricalFisherInitialization, struct ::std::default_delete< struct ::statiskit::glm::CategoricalFisherInitialization > >::pointer )= &::std::unique_ptr< struct ::statiskit::glm::CategoricalFisherInitialization, struct ::std::default_delete< struct ::statiskit::glm::CategoricalFisherInitialization > >::reset;
void  (::std::unique_ptr< ::statiskit::glm::CategoricalFisherInitialization, ::std::default_delete< ::statiskit::glm::CategoricalFisherInitialization > >::*method_pointer_b851d9dd00a95a49a7700c5cfbdc7e08)(class ::std::unique_ptr< struct ::statiskit::glm::CategoricalFisherInitialization, struct ::std::default_delete< struct ::statiskit::glm::CategoricalFisherInitialization > > &)= &::std::unique_ptr< struct ::statiskit::glm::CategoricalFisherInitialization, struct ::std::default_delete< struct ::statiskit::glm::CategoricalFisherInitialization > >::swap;

namespace autowig {
    void method_decorator_5f48b92827795a319b60334e5683e78a(class ::std::unique_ptr< struct ::statiskit::glm::CategoricalFisherInitialization, struct ::std::default_delete< struct ::statiskit::glm::CategoricalFisherInitialization > > const & instance, const struct ::statiskit::glm::CategoricalFisherInitialization & param_out) { instance.operator*() = param_out; }
}

void wrapper_4accdc07705d57999366c93a8d2e13b8(pybind11::module& module)
{

}