package:
    name: libstatiskit_glm
    version: "1.0.0"

source:
    path: ../../..

build:
    number: 0
    
about:
    home: http://statiskit-glm.readthedocs.io/
    license: Apache License 2.0
    summary: A C++ Library for Modeling Conditional Data Using Generalized Linear Models
    
requirements:
    build:
        - libtoolchain
        - libstatiskit_glm-dev
        - libstatiskit_stl
        - libstatiskit_linalg
        - libstatiskit_core
        - libboost_core-dev
    run:
        - libboost
        - libstatiskit_stl
        - libstatiskit_linalg
        - libstatiskit_core
