# -*-python-*-

Import("env")

cppenv = env.Clone(tools = ['cpp'])

cppenv.AppendUnique(CPPDEFINES = ['LIBSTATISKIT_GLM'])

exclude = """
""".split()

sources = [source for source in cppenv.Glob('*.h*') if not source.name in exclude]
targets = cppenv.CppDev("statiskit_glm", sources)
Alias("cpp-dev", targets)
Alias("cpp", targets)
Alias("autowig", targets)
Alias("install", targets)

wigenv = cppenv.Clone(tools = ['wig'])
targets = wigenv.BoostPythonWIG('statiskit_glm', [target for target in targets if target.name.endswith('.h')],
                                module='../py/wrapper/_glm.cpp',
                                decorator='../py/statiskit/glm/_glm.py',
                                parser_bootstrap=1,
                                controller='AutoWIG.py',
                                depends=['statiskit_linalg', 'statiskit_stl', 'statiskit_core'])
Alias("autowig", targets)
wigenv.Depends(targets, "cpp-dev")

exclude = """
""".split()

sources = [source for source in cppenv.Glob('*.cpp') if not source.name in exclude]
targets = cppenv.CppLib("statiskit_glm", sources)
Alias("cpp-lib", targets)
Alias("cpp", targets)
Alias("install", targets)